name: Release

on: push

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'

      - name: Build arm64 Linux
        run: |
          env GOOS=linux GOARCH=arm64 go build -o build/linux-arm64

      - name: Build amd64 Linux
        run: |
          env GOOS=linux GOARCH=amd64 go build -o build/linux-amd64

      - name: Build arm64 Windows
        run: |
          env GOOS=windows GOARCH=arm64 go build -o build/windows-arm64.exe

      - name: Build amd64 Windows
        run: |
          env GOOS=windows GOARCH=amd64 go build -o build/windows-amd64.exe

      - name: Build arm64 FreeBSD
        run: |
          env GOOS=freebsd GOARCH=arm64 go build -o build/freebsd-arm64

      - name: Build amd64 FreeBSD
        run: |
          env GOOS=freebsd GOARCH=amd64 go build -o build/freebsd-amd64

      - name: Build arm64 Darwin
        run: |
          env GOOS=darwin GOARCH=arm64 go build -o build/darwin-arm64

      - name: Build amd64 Darwin
        run: |
          env GOOS=darwin GOARCH=amd64 go build -o build/darwin-amd64

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/linux-arm64
            build/linux-amd64
            build/windows-arm64.exe
            build/windows-amd64.exe
            build/freebsd-arm64
            build/freebsd-amd64
            build/darwin-arm64
            build/darwin-amd64
